# Generated by Django 5.1 on 2024-12-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiemThiTHPT',
            fields=[
                ('sbd', models.IntegerField(primary_key=True, serialize=False)),
                ('toan', models.FloatField(blank=True, null=True)),
                ('ngu_van', models.FloatField(blank=True, null=True)),
                ('ngoai_ngu', models.FloatField(blank=True, null=True)),
                ('vat_li', models.FloatField(blank=True, null=True)),
                ('hoa_hoc', models.FloatField(blank=True, null=True)),
                ('sinh_hoc', models.FloatField(blank=True, null=True)),
                ('lich_su', models.FloatField(blank=True, null=True)),
                ('dia_li', models.FloatField(blank=True, null=True)),
                ('gdcd', models.FloatField(blank=True, null=True)),
                ('ma_ngoai_ngu', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sbd'], name='thpt_diemth_sbd_3cb4e9_idx')],
            },
        ),
    ]
